# Generated by Django 5.1.6 on 2025-03-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
