# Generated by Django 5.1.6 on 2025-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_privatechat_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
