# Generated by Django 5.1.6 on 2025-04-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0003_privatemessage_is_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
